export GRML_DISPLAY_BATTERY=1

function nix_shell_prompt () {
  if [[ -z "${IN_NIX_SHELL}" ]]; then
    REPLY=""
  else
    REPLY="${IN_NIX_SHELL}> "
  fi
}

grml_theme_add_token in-nix-shell -f nix_shell_prompt '%F{cyan}' '%f'

zstyle ':prompt:grml:left:setup' items rc change-root user at host in-nix-shell path vcs newline percent

export HEX_CDN='https://hexpm.upyun.com'
export HEX_MIRROR="$HEX_CDN"

export PATH="$PATH:$HOME/.cargo/bin"

export PATH="$PATH:$HOME/.ghcup/bin"
export PATH="$PATH:$HOME/.local/bin/flutter/bin"

alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'
export UV_PYTHON=${UV_PYTHON:-/run/current-system/sw/bin/python}
